### ISSUE TITLE
idea编译spring5报错，请教一下什么原因

### ISSUE THREAD

**Issue by androidZhy** [Vip-Augus/spring-analysis-note#3]
![image](https://user-images.githubusercontent.com/20261434/66371610-3bf9a380-e9d6-11e9-9527-83f9350318cf.png)

**Comment by Vip-Augus** [comment]
本地版本如下：
------------------------------------------------------------
Gradle 5.5.1
------------------------------------------------------------

Build time:   2019-07-10 20:38:12 UTC
Revision:     3245f748c7061472da4dc184991919810f7935a5

Kotlin:       1.3.31
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_221 (Oracle Corporation 25.221-b11)
OS:           Mac OS X 10.14.6 x86_64

使用的仓库地址都是默认的，你看下 Gradle 版本是否需要升级，如升级后还是无法编译通过，可以下载我在 release 上传的，已经是编译好的包：

https://github.com/Vip-Augus/spring-analysis-note/archive/v1.0.zip
