### ISSUE TITLE
想问一下博主学习spring源码看的是什么书呢，可以推荐以下么

### ISSUE THREAD

**Issue by xiaobie1900** [Vip-Augus/spring-analysis-note#4]
如题

**Comment by KeYangNeverCoding** [comment]
。

**Comment by Vip-Augus** [comment]
我当时买的是：Spring 源码深度解析 / 郝佳编著. -- 北京 : 人民邮电出版社。
然后一边对照书本的内容，一边看源码，遇到不懂或者想深入了解的内容，就自己 debug 和上网查详细资料。
这个工程，记录的就是当时学习笔记，你可以看下。

> 如题
